// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHk1V7zJqL8_fo6Z4irPsWo9Jm6YV9QPc',
    appId: '1:854359163211:web:ac41d4e741b0f9d79828ce',
    messagingSenderId: '854359163211',
    projectId: 'hillcrest-ride-and-share',
    authDomain: 'hillcrest-ride-and-share.firebaseapp.com',
    storageBucket: 'hillcrest-ride-and-share.firebasestorage.app',
    measurementId: 'G-XSFEG9NENG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADdY5CZd8hktGMRtLWO30t3Z_G2hRS83M',
    appId: '1:854359163211:android:68b23dd1bc7dae5f9828ce',
    messagingSenderId: '854359163211',
    projectId: 'hillcrest-ride-and-share',
    storageBucket: 'hillcrest-ride-and-share.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvtiUOx04T9FJyRCTVllKb6xz2EKfx8pw',
    appId: '1:854359163211:ios:0b86bc0678d0a7399828ce',
    messagingSenderId: '854359163211',
    projectId: 'hillcrest-ride-and-share',
    storageBucket: 'hillcrest-ride-and-share.firebasestorage.app',
    iosBundleId: 'com.example.appForHillcrest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvtiUOx04T9FJyRCTVllKb6xz2EKfx8pw',
    appId: '1:854359163211:ios:0b86bc0678d0a7399828ce',
    messagingSenderId: '854359163211',
    projectId: 'hillcrest-ride-and-share',
    storageBucket: 'hillcrest-ride-and-share.firebasestorage.app',
    iosBundleId: 'com.example.appForHillcrest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHk1V7zJqL8_fo6Z4irPsWo9Jm6YV9QPc',
    appId: '1:854359163211:web:0c5e29545464f8aa9828ce',
    messagingSenderId: '854359163211',
    projectId: 'hillcrest-ride-and-share',
    authDomain: 'hillcrest-ride-and-share.firebaseapp.com',
    storageBucket: 'hillcrest-ride-and-share.firebasestorage.app',
    measurementId: 'G-3P3NC57WE0',
  );
}
