import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

import '../theme/app_theme.dart';
import '../data/translations.dart';
import '../services/ride_service.dart';
import '../services/auth_service.dart';
import '../models/ride_request.dart';

class RequestManageRidePage extends StatefulWidget {
  const RequestManageRidePage({super.key});

  @override
  State<RequestManageRidePage> createState() => _RequestManageRidePageState();
}

class _RequestManageRidePageState extends State<RequestManageRidePage> {
  final _formKey = GlobalKey<FormState>();
  final _dateController = TextEditingController();
  final _nameController = TextEditingController();
  final _phoneController = TextEditingController();
  final _fromController = TextEditingController();
  final _toController = TextEditingController();
  final _reasonController = TextEditingController();
  bool _isSubmitting = false;

  @override
  void dispose() {
    _dateController.dispose();
    _nameController.dispose();
    _phoneController.dispose();
    _fromController.dispose();
    _toController.dispose();
    _reasonController.dispose();
    super.dispose();
  }

  Future<void> _handleSubmit() async {
    if (_formKey.currentState!.validate()) {
      setState(() => _isSubmitting = true);
      
      final currentUser = AuthService().currentUser;
      
      final ride = RideRequest(
        id: '', // Will be generated by Firestore
        participantName: _nameController.text,
        dateLabel: _dateController.text,
        pickupTime: 'TBD', // Simplified for now
        dropoffTime: 'TBD',
        fromAddress: _fromController.text,
        toAddress: _toController.text,
        phone: _phoneController.text,
        reason: _reasonController.text,
        status: RideStatus.unassigned,
        requesterUid: currentUser?.uid,
        driverName: null,
        // Adding dummy coordinates for Platte City so it shows up on the map
        // Adding a small random offset so multiple requests don't overlap perfectly
        departureLocation: LatLng(
          39.3708 + (DateTime.now().millisecond % 100) / 10000, 
          -94.7816 + (DateTime.now().second % 100) / 10000
        ),
        arrivalLocation: LatLng(
          39.3750 + (DateTime.now().millisecond % 100) / 10000, 
          -94.7850 + (DateTime.now().second % 100) / 10000
        ),
      );

      await RideService().requestRide(ride);
      
      setState(() => _isSubmitting = false);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(TranslationService.translate('ride_submitted')),
            behavior: SnackBarBehavior.floating,
          ),
        );
        Navigator.pop(context);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder(
      valueListenable: TranslationService.currentLanguage,
      builder: (context, lang, _) {
        return Scaffold(
          backgroundColor: AppTheme.background,
          body: SafeArea(
            child: SingleChildScrollView(
              physics: const BouncingScrollPhysics(),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Header section
                  Padding(
                    padding: const EdgeInsets.fromLTRB(24, 20, 24, 8),
                    child: Row(
                      children: [
                        IconButton(
                          onPressed: () => Navigator.pop(context),
                          icon: const Icon(Icons.arrow_back_ios_new, size: 20),
                          style: IconButton.styleFrom(
                            backgroundColor: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                          ),
                        ),
                        const SizedBox(width: 16),
                        Text(
                          TranslationService.translate('request_ride_title'),
                          style: const TextStyle(
                            fontSize: 24,
                            fontWeight: FontWeight.w800,
                            color: Colors.black87,
                          ),
                        ),
                      ],
                    ),
                  ),

                  Padding(
                    padding: const EdgeInsets.all(24.0),
                    child: Form(
                      key: _formKey,
                      child: Column(
                        children: [
                          // Section 1: Personal Info
                          _buildFormSection(
                            title: TranslationService.translate('personal_details'),
                            children: [
                              _buildModernField(
                                label: TranslationService.translate('full_name'),
                                controller: _nameController,
                                icon: Icons.person_outline,
                              ),
                              const SizedBox(height: 16),
                              _buildModernField(
                                label: TranslationService.translate('phone_number'),
                                controller: _phoneController,
                                icon: Icons.phone_outlined,
                                keyboardType: TextInputType.phone,
                              ),
                            ],
                          ),
                          const SizedBox(height: 24),

                          // Section 2: Ride Details
                          _buildFormSection(
                            title: TranslationService.translate('ride_details'),
                            children: [
                              _buildModernField(
                                label: TranslationService.translate('ride_date'),
                                controller: _dateController,
                                icon: Icons.calendar_today_outlined,
                              ),
                              const SizedBox(height: 16),
                              _buildModernField(
                                label: TranslationService.translate('departure_address'),
                                controller: _fromController,
                                icon: Icons.circle_outlined,
                              ),
                              const SizedBox(height: 16),
                              _buildModernField(
                                label: TranslationService.translate('arrival_address'),
                                controller: _toController,
                                icon: Icons.location_on_outlined,
                              ),
                            ],
                          ),
                          const SizedBox(height: 24),

                          // Section 3: Preferences
                          _buildFormSection(
                            title: TranslationService.translate('preferences_label'),
                            children: [
                              _buildModernField(
                                label: TranslationService.translate('reason_for_ride'),
                                controller: _reasonController,
                                icon: Icons.help_outline,
                              ),
                            ],
                          ),

                          const SizedBox(height: 40),

                          // Action Buttons
                          SizedBox(
                            width: double.infinity,
                            height: 56,
                            child: ElevatedButton(
                              onPressed: _isSubmitting ? null : _handleSubmit,
                              style: ElevatedButton.styleFrom(
                                backgroundColor: AppTheme.primaryGreen,
                                foregroundColor: Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(16),
                                ),
                                elevation: 0,
                              ),
                              child: _isSubmitting 
                                ? const CircularProgressIndicator(color: Colors.white)
                                : Text(
                                    TranslationService.translate('submit_request'),
                                    style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w700),
                                  ),
                            ),
                          ),
                          const SizedBox(height: 16),
                          TextButton.icon(
                            onPressed: () {
                              _formKey.currentState?.reset();
                              _dateController.clear();
                              _nameController.clear();
                              _phoneController.clear();
                              _fromController.clear();
                              _toController.clear();
                              _reasonController.clear();
                            },
                            icon: const Icon(Icons.refresh_rounded, color: Colors.black45),
                            label: Text(
                              TranslationService.translate('clear_form'),
                              style: const TextStyle(color: Colors.black45, fontWeight: FontWeight.w600),
                            ),
                          ),
                          const SizedBox(height: 24),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  Widget _buildFormSection({required String title, required List<Widget> children}) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(24),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.03),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.w700,
              color: AppTheme.primaryGreen.withOpacity(0.8),
              letterSpacing: 1.1,
            ),
          ),
          const SizedBox(height: 20),
          ...children,
        ],
      ),
    );
  }

  Widget _buildModernField({
    required String label,
    required TextEditingController controller,
    required IconData icon,
    TextInputType keyboardType = TextInputType.text,
  }) {
    return TextFormField(
      controller: controller,
      keyboardType: keyboardType,
      validator: (value) => (value == null || value.trim().isEmpty) ? 'Required' : null,
      decoration: InputDecoration(
        labelText: label,
        labelStyle: const TextStyle(color: Colors.black45, fontWeight: FontWeight.w500),
        prefixIcon: Icon(icon, color: AppTheme.primaryGreen.withOpacity(0.7)),
        filled: true,
        fillColor: AppTheme.background.withOpacity(0.5),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide.none,
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: const BorderSide(color: AppTheme.primaryGreen, width: 1.5),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 18),
      ),
    );
  }
}
